language: node_js

node_js:
 - "7"

cache:
 directories:
  - node_modules

before_script:
 - npm install -g hexo-cli
 - git clone --branch master https://github.com/wangjin252/github.io master
 - cd master
 - npm install

script:
 - hexo clean
 - hexo g

after_script:
 - hexo d
