language: node_js

node_js:
 - "7"

#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: ba90ed4e81a7eb2ee04bf470cdd049e65ba58766 # Set in travis-ci.org dashboard
#  on:
#    branch: master

cache:
 directories:
  - node_modules

before_script:
 - npm install -g hexo-cli
 - git clone --branch master https://github.com/wangjin252/github.io master
 - git config --global user.email "wangjin-252@hotmail.com"
 - git config --global user.name "wangjin252"
 - cd master
 - npm install

script:
 - hexo clean
 - hexo g

after_success:
 - hexo d
